### ISSUE TITLE
picom-next-ibhagwan not building

### ISSUE THREAD

**Issue by Apppppppple** [reedrw/nur-packages#55]
When I build picom it errors with
```
Compiling C object src/picom.p/picom.c.oninja: fatal: posix_spawn: No such file or directory
```

**Comment by reedrw** [comment]
What nixpkgs commit are you building this from? I can't get this error on my machine?

**Comment by Apppppppple** [comment]
I'm on the unstable channel but idk if that's what you mean - I'm pretty new to nixos sorry. Just got the same error today while trying to build a different package so it looks like it's something messed up in my config.
